### ISSUE TITLE
cannot subtract area from vegetation

### ISSUE THREAD

**Issue by guruthree** [mike-brown/ponds-online#23] opened 2017-07-03 13:50 UTC
![screenshot at 2017-07-03 14-50-04](https://user-images.githubusercontent.com/3973507/27795684-f5a6c772-5ffe-11e7-8212-861aee6ee412.png)

**Comment by robjtede** [comment] 2017-07-03 13:52
related to/duplicate of #20

**Closed as completed** 2017-07-05 15:19 UTC
Labels: bug, duplicate, pond-editor
